### ISSUE TITLE
Error uploading bundles

### ISSUE THREAD

**Issue by Almighty-Alpaca** [Vacxe/google-play-cli-kt#20]
Hi, I'm trying to use the CLI to upload an AppBundle to the Play Store. I'm using the Docker image with `$PWD` mounted to `/config` and get the following error:

```
$ export PLAYSTORE_SERVICE_ACCOUNT_JSON_FILE=<redacted>
$ export APP_PACKAGE_NAME=<redacted>
$ google-play-cli apk list
{"kind":"androidpublisher#apksListResponse"}
$ edit_id=$(google-play-cli edit create)
$ google-play-cli bundles upload --edit-id $edit_id --bundle app.aab
Exception in thread "main" com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
PUT https://www.googleapis.com/upload/androidpublisher/v3/applications/<redacted>/edits/<redacted>/bundles?ackBundleInstallationWarning=false&uploadType=resumable&upload_id=<redacted>
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Media type 'application/vnd.android.package-archive' is not supported. ",
    "reason" : "badRequest"
  } ],
  "message" : "Media type 'application/vnd.android.package-archive' is not supported. ",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.github.vacxe.googleplaycli.actions.Bundles$DefaultImpls.bundlesUpload(Bundles.kt:25)
        at com.github.vacxe.googleplaycli.PlayStoreApi.bundlesUpload(PlayStoreApi.kt:14)
        at com.github.vacxe.googleplaycli.Commands$Bundles$Upload.run(Commands.kt:33)
        at com.github.vacxe.googleplaycli.Commands$Bundles$Upload.run(Commands.kt:28)
        at com.github.vacxe.googleplaycli.core.BaseCommand.run(BaseCommand.kt:52)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at com.github.vacxe.googleplaycli.PlayStoreCliKt.main(PlayStoreCli.kt:89)
```

Is there any workaround for this?

**Comment by Almighty-Alpaca** [comment]
I've just had a bit of time to investigate and found the problem. `application/vnd.android.package-archive` is for APK files specificallym which for obvious reasons doesn't work for app bundles. it seems like this is a leftover from copy/pasting the code for APKs. I have confirmed that using the generic `application/octet-stream` works without any issues,

**Comment by Almighty-Alpaca** [comment]
If anyone else is having the same issue as me I've uploaded a Docker image with this fix as [`almightyalpaca/google-play-cli:fix-bundle-upload`](https://hub.docker.com/layers/almightyalpaca/google-play-cli/fix-bundle-upload/images/sha256-ce74699e27382a43bd893593efe55ccd5ee455c20234341b4dba5615ae68e850?context=explore)
